---
id: ruby200-regexp
base_name: ruby200-regexp
tags:
- onigmo
- oniguruma
- regexp
- ruby
- ruby2.0
presentation_date: 2013/06/02
version: 1.0.1
licenses: []
slideshare_id: ruby200-regexp-22312775
speaker_deck_id: 
ustream_id: 
vimeo_id: 
author:
  markup_language: :rd
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: 
